language: node_js

node_js:
- 10

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

script:
  # start server in the background
  - npm run dev &
  # run all Cypress tests and record on the dashboard
  # the projectId and key from testRunner > runs configurations (cypress test interface)
  # - npm test -- --record --key f6a7ebca-cb26-484f-890b-7ddace40c918
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  # this avoids flake in Travis jobs
  - kill $(jobs -p) || true